// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvKSAKh59VFBosNNpU2mHN5LTPwdnzqq8',
    appId: '1:1037700937152:web:522cf6a7aa156b172fc425',
    messagingSenderId: '1037700937152',
    projectId: 'chat-app-2010034190',
    authDomain: 'chat-app-2010034190.firebaseapp.com',
    storageBucket: 'chat-app-2010034190.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWDuc_7z4MDUFrH1ZbLBtZ8vPgi2CKWhA',
    appId: '1:1037700937152:android:a4f16590d3303b5c2fc425',
    messagingSenderId: '1037700937152',
    projectId: 'chat-app-2010034190',
    storageBucket: 'chat-app-2010034190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlqy1qTG6114Uf7SLkNd4WImYB83LWsgo',
    appId: '1:1037700937152:ios:e6986020c21208972fc425',
    messagingSenderId: '1037700937152',
    projectId: 'chat-app-2010034190',
    storageBucket: 'chat-app-2010034190.appspot.com',
    iosClientId:
        '1037700937152-tp73g2eg9ted2eq239pvgdknmdc9gd29.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
